name: CMake

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read
      packages: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup NuGet
      shell: pwsh
      run: |
        nuget sources add `
          -source "https://nuget.pkg.github.com/PurpleFlowerGarden/index.json" `
          -storepasswordincleartext `
          -name "${env:NUGET_REPOSITORY_ID}" `
          -username "${{ github.repository_owner }}" `
          -password "${{ secrets.GITHUB_TOKEN }}"
        nuget setapikey `
          "${{ secrets.GITHUB_TOKEN }}" `
          -source "${env:NUGET_REPOSITORY_ID}"
        nuget sources

    - name: Find VCPKG
      shell: pwsh
      run: |
        cd "c:/Program Files"
        mkdir test

