name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: ['ubuntu-22.04', 'ubuntu-22.04-dynamic', 'windows-2022']
        build_type: ['debug', 'release']
        include:
          - target: 'ubuntu-22.04'
            runner: 'ubuntu-22.04'
          - target: 'ubuntu-22.04-dynamic'
            runner: 'ubuntu-22.04'
          - target: 'windows-2022'
            runner: 'windows-2022'
        
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Ubuntu
      if: ${{ matrix.runner == 'ubuntu-22.04' }}
      run: |
        sudo apt update
        sudo apt install -y glib-dev

    - name: Configure
      working-directory: ${{github.workspace}}
      run: cmake --preset gh-${{matrix.target}}-${{matrix.build_type}}
      
    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build --preset gh-${{matrix.target}}-${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}
      run: ctest --preset gh-${{matrix.target}}-${{matrix.build_type}}

